---
- hosts: all
  become: yes
  tasks:

    - name: add zabbix userparameter for fail2ban
      tags:
         - userparameter   
      copy:
        src: fail2ban.conf
        dest: /etc/zabbix/zabbix_agentd.d/fail2ban.conf

    - name: restart zabbix-agent
      tags:
         - userparameter   
      service:
        name: zabbix-agent
        state: restarted